DELETE from Canister
DELETE from CanisterHistory
DELETE from CanisterPill
DELETE from CanisterPillHistory
DELETE from Consumable
DELETE from ConsumableHistory
DELETE from ContactAddress
DELETE from ContactAddressHistory
DELETE from ContactPerson
DELETE from ContactPersonHistory
DELETE from Customer
DELETE from CustomerHistory
DELETE from DestinationFacility
DELETE from DestinationFacilityHistory
DELETE from ExternalSourceInfo
DELETE from ExternalSourceInfoHistory
DELETE from InternalOrder
DELETE from InternalOrderHistory
DELETE from InternalOrderOverview
DELETE from MachineOrder
DELETE from MachineOrderHistory
DELETE from Medicine
DELETE from MedicineHistory
DELETE from MedicineContainer
DELETE from MedicineContainerHistory
DELETE from MedicineContent
DELETE from MedicineContentHistory
DELETE from OrderDetail
DELETE from OrderDetailHistory
